version: '3.4'

services:
  rhmnproject:
    image: rhmnproject
    build:
      context: rhmnproject
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
